# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4235963e8439c9c99e3c0dff741ccc4db5c0bbb2c9b2b1e3c96dab6ba4a0d876fddf9574d4f6316f41aa362b690f9bf6552d3c70fae2a84bc10b15962058343d

test:
  secret_key_base: 957bef7bbc64d1b91a4961141a293b6ac7bbe272be911f24f87e8efa4a0800a734b9cc9fc07635d11fb00cf938eed43f55c875f74d79dd79a4a3fce5626614c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
